create database db_compass character set = 'utf8' collate = 'utf8_general_ci';

use db_compass;

CREATE TABLE IF NOT EXISTS tb_proposta (
    cd_proposta INT NOT NULL AUTO_INCREMENT,
    nm_responsável_proposta VARCHAR(100),
    nm_email_responsavel_proposta VARCHAR(100),
    nm_cargo_responsavel_proposta VARCHAR(100),
    dt_proposta DATE,
    nr_ref_acl CHAR(2),
    nr_proposta INT,
    nr_versao_proposta DOUBLE,
    nm_ref_cliente VARCHAR(100),
    hr_recebimento DATETIME,
    nm_produto VARCHAR(100),
    qt_embalagem INT,
    vl_peso_total_cubagem DOUBLE,
    nm_empresa VARCHAR(100),
    nm_contato_empresa VARCHAR(100),
    nm_email_contato_empresa VARCHAR(100),
    nm_tipo_frete VARCHAR(100),
    sg_uf_origem CHAR(2),
    nm_cidade_origem VARCHAR(50),
    sg_uf_destino CHAR(2),
    nm_cidade_destino VARCHAR(50),
    nm_local_devolucao VARCHAR(500),
    nm_tipo_container VARCHAR(100),
    nm_tipo_veiculo VARCHAR(100),
    qt_eixos_veiculo INT,
    nm_tipo_operacao VARCHAR(100),
    nm_tipo_imposto_operacao VARCHAR(100),
    vl_mercadoria_operacao DECIMAL(20 , 2 ),
    vl_container_operacao DECIMAL(20 , 2 ),
    pc_imp_susp_operacao DOUBLE,
    vl_imp_susp_operacao DECIMAL(20 , 2 ),
    vl_total_imp_seg_operacao DECIMAL(20 , 2 ),
    vl_frete_peso_operacao DECIMAL(20 , 2 ),
    pc_rctrc_operacao DOUBLE,
    vl_rctrc_operacao DECIMAL(20 , 2 ),
    pc_rcfdc_operacao DOUBLE,
    vl_rcfdc_operacao DECIMAL(20 , 2 ),
    id_gris_operacao VARCHAR(10),
    pc_gris_operacao DOUBLE,
    vl_total_gris_operacao DECIMAL(20 , 2 ),
    vl_pedagio_operacao DECIMAL(20 , 2 ),
    vl_estacionamento_operacao DECIMAL(20 , 2 ),
    cd_imo_operacao INT,
    cd_dta_operacao INT,
    vl_ajudantes_operacao DECIMAL(20 , 2 ),
    pc_icms_operacao DOUBLE,
    vl_icms_operacao DECIMAL(20 , 2 ),
    vl_sub_total_operacao DECIMAL(20 , 2 ),
    vl_total_prest_operacao DECIMAL(20 , 2 ),
    pc_total_prest_operacao DOUBLE,
    vl_despesas_operacao DECIMAL(20 , 2 ),
    pc_lucro_bruto_operacao DOUBLE,
    vl_lucro_bruto_operacao DECIMAL(20 , 2 ),
    nm_motorista_aut_despesas VARCHAR(100),
    vl_pedagio_motorista_despesas DECIMAL(20 , 2 ),
    pc_rcfdc_despesas DOUBLE,
    vl_rcfdc_despesas DECIMAL(20 , 2 ),
    pc_rctrc_despesas DOUBLE,
    vl_rctrc_despesas DECIMAL(20 , 2 ),
    pc_simples_nac_despesas DOUBLE,
    vl_simples_nac_despesas DECIMAL(20 , 2 ),
    pc_irpj_despesas DOUBLE,
    vl_irpj_despesas DECIMAL(20 , 2 ),
    pc_adic_irpj_despesas DOUBLE,
    vl_adic_irpj_despesas DECIMAL(20 , 2 ),
    pc_pis_despesas DOUBLE,
    vl_pis_despesas DECIMAL(20 , 2 ),
    pc_cofins_despesas DOUBLE,
    vl_cofins_despesas DECIMAL(20 , 2 ),
    pc_icms_despesas DOUBLE,
    vl_icms_despesas DECIMAL(20 , 2 ),
    cd_buonny_cad_despesas INT,
    vl_gris_rast_despesas DECIMAL(20 , 2 ),
    vl_dta_di_terc_despesas DECIMAL(20 , 2 ),
    vl_estacionamento_despesas DECIMAL(20 , 2 ),
    vl_ajudantes_despesas DECIMAL(20 , 2 ),
    vk_profit_despesas DECIMAL(20 , 2 ),
    vl_comissao_despesas DECIMAL(20 , 2 ),
    pc_comissao_despesas DOUBLE,
    vl_despesas DECIMAL(20 , 2 ),
    nm_tipo_carga VARCHAR(100),
    qt_eixos_carga INT,
    qt_km_ida_carga DOUBLE,
    qt_km_volta_carga DOUBLE,
    qt_total_km_carga DOUBLE,
    vl_pedagio_ida_eixo_carga DECIMAL(20 , 2 ),
    vl_pedagio_volta_eixo_carga DECIMAL(20 , 2 ),
    qt_consumo_medio_km_lit_carga DOUBLE,
    vl_preco_litro_comb_carga DECIMAL(20 , 2 ),
    qt_comb_total_lit_carga DOUBLE,
    vl_total_comb_carga DECIMAL(20 , 2 ),
    vl_total_pedagio_carga DECIMAL(20 , 2 ),
    vl_despesa_total_viagem_carga DECIMAL(20 , 2 ),
    vl_usd_eur_carga DECIMAL(20 , 2 ),
    nm_moeda_carga VARCHAR(50),
    vl_cotacao_carga DECIMAL(20 , 2 ),
    vl_brl_carga DECIMAL(20 , 2 ),
    vl_valores_motorista DECIMAL(20 , 2 ),
    vl_frete_conf_antt_motorista DECIMAL(20 , 2 ),
    vl_pedagio_tab_motorista DECIMAL(20 , 2 ),
    vl_total_aut_tab_motorista DECIMAL(20 , 2 ),
    vl_lucro_total_aut_tab_motorista DECIMAL(20 , 2 ),
    vl_frete_all_in_fechado_motorista DECIMAL(20 , 2 ),
    vl_lucro_frete_all_in_fechado_motorista DECIMAL(20 , 2 ),
    vl_tentar_fechar_motorista DECIMAL(20 , 2 ),
    vl_lucro_tentar_fechar_motorista DECIMAL(20 , 2 ),
    nm_motorista_cotacao VARCHAR(100),
    dt_cotacao DATE,
    vl_cotacao DECIMAL(20 , 2 )
);

CREATE TABLE IF NOT EXISTS tb_icms (
    cd_icms INT NOT NULL AUTO_INCREMENT,
    sg_icms VARCHAR(10),
    pc_icms DOUBLE,
    CONSTRAINT pk_icms PRIMARY KEY (cd_icms)
);
